---
kind: "operation"
client: "atomist-bot"
generator:
  name: "NewRugProject"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.29.0"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "0f425945c62957ccc2ccb63e9980e6f78b97a4a1"
    sha: "0f42594"
  parameters:
    - "owner": "com.qingtian"
    - "description": "rug-demo"
    - "version": "0.1.0"

